const actionTypes = {
  CHANGE_CREDENTIAL: "CHANGE_CREDENTIAL",
  CHANGE_USER: "CHANGE_USER",
  CHANGE_PASS: "CHANGE_PASS",
  SUBMIT_CREDENTIALS: "SUBMIT_CREDENTIALS",
};

export default actionTypes;
