const actionTypes = {
    CHANGE_USER: "CHANGE_USER",
    CHANGE_PASS: "CHANGE_PASS",
    SUBMIT_CREDENTIALS: "SUBMIT_CREDENTIALS",
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    CHANGE_CREDENTIAL_STORED: "CHANGE_CREDENTIAL_STORED",
    CHANGE_CREDENTIAL_USER: "CHANGE_CREDENTIAL_USER"
};

export default actionTypes;
