const actionTypes = {
  CHANGE_CREDENTIAL: 'CHANGE_CREDENTIAL',
  CHANGE_CREDENTIAL_USER: 'CHANGE_CREDENTIAL_USER',
  CHANGE_CREDENTIAL_STORED: 'CHANGE_CREDNETIAL_STORED',
  CHANGE_USER: 'CHANGE_USER',
  CHANGE_PASS: 'CHANGE_PASS',
  SUBMIT_CREDENTIALS: 'SUBMIT_CREDENTIALS',
};

export default actionTypes;
